### ISSUE TITLE
ML Modules 0.5.4: Counter length behaviors

### ISSUE THREAD

**Issue by DomiKamu** [martin-lueders/ML_modules#34] opened 2018-01-28 05:33 UTC
Platform: Windows 7 Pro SP1 x64 (French-localized).
VCV Rack v0.5.1
ML Modules v0.5.4

Hi Martin,

I'd like to report a strange behavior (discovered by "chance") about multiple instances of Counter module in a patch. When I'm using only one Counter module (doesn't matter if connected or not, and of course, Length CV isn't connected), when you turn the "Length" knob to max, it displays 127 (assuming it's normal).

But, if your add a second Counter module (unconnected), as soon as you change its Length parameter, the first Counter "Length" change by itself from 127 to 128. This behavior doesn't occur if the value is less than 127, however.

Regards.

**Comment by martin-lueders** [comment] 2018-01-29 00:01
Thanks for the report. 

I can reproduce the problem, but to be honest, so far I have no clue what is happening.
I have not declared any variables as static, so I don't understand where that "cross talk" is coming from. I will need to investigate that further.

**Comment by martin-lueders** [comment] 2018-01-30 14:49
I still don't know what exactly caused the cross-talk, but I realized that actually the limit to 127 was wrong, due to a missing round() function. I added the rounding now, and the issue seems to be fixed.

Will be in the next release.

**Closed** 2018-02-01 12:09 UTC
